---
apiVersion: v1
kind: Namespace
metadata:
  name: customer-portal

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: customer-portal
data:
  init.sql: |
    -- Customer Portal Database Schema
    
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        email VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE products (
        id SERIAL PRIMARY KEY,
        name VARCHAR(200),
        price DECIMAL(10,2),
        category VARCHAR(50)
    );
    
    CREATE TABLE orders (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE order_items (
        id SERIAL PRIMARY KEY,
        order_id INTEGER REFERENCES orders(id),
        product_id INTEGER REFERENCES products(id),
        quantity INTEGER
    );
    
    CREATE TABLE reviews (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        product_id INTEGER REFERENCES products(id),
        rating INTEGER
    );
    
    -- Insert substantial test data to make queries slow
    INSERT INTO users (name, email) 
    SELECT 
        'Customer ' || i,
        'customer' || i || '@example.com'
    FROM generate_series(1, 2000) i;
    
    INSERT INTO products (name, price, category)
    SELECT 
        'Product ' || i,
        (random() * 200 + 10)::DECIMAL(10,2),
        CASE (i % 4) 
            WHEN 0 THEN 'Electronics'
            WHEN 1 THEN 'Clothing'
            WHEN 2 THEN 'Home'
            ELSE 'Books'
        END
    FROM generate_series(1, 800) i;
    
    INSERT INTO orders (user_id, order_date)
    SELECT 
        (random() * 1999 + 1)::INTEGER,
        CURRENT_TIMESTAMP - (random() * interval '365 days')
    FROM generate_series(1, 8000) i;
    
    INSERT INTO order_items (order_id, product_id, quantity)
    SELECT 
        (random() * 7999 + 1)::INTEGER,
        (random() * 799 + 1)::INTEGER,
        (random() * 3 + 1)::INTEGER
    FROM generate_series(1, 25000) i;
    
    INSERT INTO reviews (user_id, product_id, rating)
    SELECT 
        (random() * 1999 + 1)::INTEGER,
        (random() * 799 + 1)::INTEGER,
        (random() * 5 + 1)::INTEGER
    FROM generate_series(1, 12000) i;
    
    -- Intentionally NO indexes on foreign keys to ensure slow performance

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: customer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "customerdb"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: init-sql
        configMap:
          name: postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: customer-portal
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal-app
  namespace: customer-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      containers:
      - name: webapp
        image: your-registry/customer-portal:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service"  # Matches your K8s PostgreSQL service name
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres123"
        - name: DB_NAME
          value: "customerdb"
        - name: DB_PORT
          value: "5432"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer-portal-service
  namespace: customer-portal
spec:
  selector:
    app: customer-portal
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer